#include "app.h"

/* Generated by tools/gen_icm.py. Do not edit by hand. */

#define COUNT(a) ((uint8_t)(sizeof(a) / sizeof((a)[0])))

static void draw_x_est_1(void) {
    g_line(80, 100, 180, 100, COL_GRAY);
    g_line(180, 100, 180, 200, COL_GRAY);
    g_line(180, 200, 80, 200, COL_GRAY);
    g_line(80, 200, 80, 100, COL_GRAY);
    g_line(120, 60, 220, 60, COL_GRAY);
    g_line(220, 60, 220, 160, COL_GRAY);
    g_line(220, 160, 120, 160, COL_GRAY);
    g_line(120, 160, 120, 60, COL_GRAY);
    g_line(80, 100, 120, 60, COL_GRAY);
    g_line(180, 100, 220, 60, COL_GRAY);
    g_line(180, 200, 220, 160, COL_GRAY);
    g_line(80, 200, 120, 160, COL_GRAY);
    g_disc(80, 100, 6, COL_LIGHT);
    g_disc(180, 100, 6, COL_LIGHT);
    g_disc(180, 200, 6, COL_LIGHT);
    g_disc(80, 200, 6, COL_LIGHT);
    g_disc(120, 60, 6, COL_LIGHT);
    g_disc(220, 60, 6, COL_LIGHT);
    g_disc(220, 160, 6, COL_LIGHT);
    g_disc(120, 160, 6, COL_LIGHT);
    g_disc(130, 150, 6, COL_LIGHT);
    g_disc(170, 110, 6, COL_LIGHT);
    g_disc(100, 130, 6, COL_LIGHT);
    g_disc(200, 130, 6, COL_LIGHT);
    g_disc(150, 80, 6, COL_LIGHT);
    g_disc(150, 180, 6, COL_LIGHT);
}

static void draw_x_est_2(void) {
    g_line(80, 100, 180, 100, COL_GRAY);
    g_line(180, 100, 180, 200, COL_GRAY);
    g_line(180, 200, 80, 200, COL_GRAY);
    g_line(80, 200, 80, 100, COL_GRAY);
    g_line(120, 60, 220, 60, COL_GRAY);
    g_line(220, 60, 220, 160, COL_GRAY);
    g_line(220, 160, 120, 160, COL_GRAY);
    g_line(120, 160, 120, 60, COL_GRAY);
    g_line(80, 100, 120, 60, COL_GRAY);
    g_line(180, 100, 220, 60, COL_GRAY);
    g_line(180, 200, 220, 160, COL_GRAY);
    g_line(80, 200, 120, 160, COL_GRAY);
    g_disc(80, 100, 6, COL_LIGHT);
    g_disc(180, 100, 6, COL_LIGHT);
    g_disc(180, 200, 6, COL_LIGHT);
    g_disc(80, 200, 6, COL_LIGHT);
    g_disc(120, 60, 6, COL_LIGHT);
    g_disc(220, 60, 6, COL_LIGHT);
    g_disc(220, 160, 6, COL_LIGHT);
    g_disc(120, 160, 6, COL_LIGHT);
    g_disc(150, 130, 7, COL_LIGHT);
}

static void draw_x_den_1(void) {
    g_line(80, 100, 180, 100, COL_GRAY);
    g_line(180, 100, 180, 200, COL_GRAY);
    g_line(180, 200, 80, 200, COL_GRAY);
    g_line(80, 200, 80, 100, COL_GRAY);
    g_line(120, 60, 220, 60, COL_GRAY);
    g_line(220, 60, 220, 160, COL_GRAY);
    g_line(220, 160, 120, 160, COL_GRAY);
    g_line(120, 160, 120, 60, COL_GRAY);
    g_line(80, 100, 120, 60, COL_GRAY);
    g_line(180, 100, 220, 60, COL_GRAY);
    g_line(180, 200, 220, 160, COL_GRAY);
    g_line(80, 200, 120, 160, COL_GRAY);
    g_disc(80, 100, 6, COL_LIGHT);
    g_disc(180, 100, 6, COL_LIGHT);
    g_disc(180, 200, 6, COL_LIGHT);
    g_disc(80, 200, 6, COL_LIGHT);
    g_disc(120, 60, 6, COL_LIGHT);
    g_disc(220, 60, 6, COL_LIGHT);
    g_disc(220, 160, 6, COL_LIGHT);
    g_disc(120, 160, 6, COL_LIGHT);
    g_disc(130, 150, 6, COL_LIGHT);
    g_disc(170, 110, 6, COL_LIGHT);
    g_disc(100, 130, 6, COL_LIGHT);
    g_disc(200, 130, 6, COL_LIGHT);
    g_disc(150, 80, 6, COL_LIGHT);
    g_disc(150, 180, 6, COL_LIGHT);
}

static void draw_x_dif_1(void) {
    g_axes(55, 56, 295, 205);
    g_text("C", 38, 50, COL_GRAY);
    g_text("x", 270, 210, COL_GRAY);
    g_line(70, 80, 250, 170, COL_BLUE);
    g_dash(70, 80, 70, 205, COL_GRAY);
    g_dash(250, 170, 250, 205, COL_GRAY);
    g_text("CA", 75, 70, COL_BLACK);
    g_text("CB", 230, 150, COL_BLACK);
    g_text("dx", 150, 188, COL_GRAY);
}

static void draw_x_dif_2(void) {
    g_axes(55, 56, 295, 205);
    g_text("C", 38, 50, COL_GRAY);
    g_text("x", 270, 210, COL_GRAY);
    g_line(70, 80, 250, 170, COL_BLUE);
    g_dash(70, 80, 70, 205, COL_GRAY);
    g_dash(250, 170, 250, 205, COL_GRAY);
    g_text("CA", 75, 70, COL_BLACK);
    g_text("CB", 230, 150, COL_BLACK);
    g_text("dx", 150, 188, COL_GRAY);
}

static void draw_x_arr_2(void) {
    g_axes(55, 56, 295, 205);
    g_text("lnD", 30, 50, COL_GRAY);
    g_text("1/T", 264, 210, COL_GRAY);
    g_line(75, 80, 260, 185, COL_BLUE);
    g_dot(110, 100, COL_RED);
    g_dot(220, 162, COL_RED);
    g_text("(1/T1,lnD1)", 110, 86, COL_BLACK);
    g_text("(1/T2,lnD2)", 150, 168, COL_BLACK);
}

static void draw_x_dia_1(void) {
    g_axes(55, 56, 295, 205);
    g_text("T", 38, 50, COL_GRAY);
    g_text("%Sn", 262, 210, COL_GRAY);
    g_line(60, 70, 190, 150, COL_BLUE);
    g_line(190, 150, 285, 95, COL_BLUE);
    g_line(95, 150, 250, 150, COL_BLACK);
    g_dot(190, 150, COL_RED);
    g_line(60, 150, 95, 150, COL_RED);
    g_line(285, 150, 250, 150, COL_RED);
    g_text("L", 150, 90, COL_BLUE);
    g_text("a", 80, 175, COL_RED);
    g_text("b", 255, 175, COL_RED);
    g_text("E", 196, 140, COL_BLACK);
}

static void draw_x_ala_1(void) {
    g_axes(55, 56, 295, 205);
    g_text("T", 38, 50, COL_GRAY);
    g_text("%B", 270, 210, COL_GRAY);
    g_line(55, 70, 130, 95, COL_BLUE);
    g_line(130, 95, 210, 130, COL_BLUE);
    g_line(210, 130, 285, 175, COL_BLUE);
    g_line(55, 70, 140, 130, COL_RED);
    g_line(140, 130, 220, 165, COL_RED);
    g_line(220, 165, 285, 175, COL_RED);
    g_dash(120, 120, 210, 120, COL_BLACK);
    g_dot(120, 120, COL_RED);
    g_dot(210, 120, COL_BLUE);
    g_dot(165, 120, COL_BLACK);
    g_text("L", 240, 80, COL_BLUE);
    g_text("a", 90, 175, COL_RED);
    g_text("a+L", 150, 100, COL_BLACK);
}

static void draw_x_mec_1(void) {
    g_axes(55, 56, 295, 205);
    g_text("sig", 30, 50, COL_GRAY);
    g_text("eps", 270, 210, COL_GRAY);
    g_line(55, 205, 120, 120, COL_BLUE);
    g_line(120, 120, 160, 95, COL_BLUE);
    g_line(160, 95, 210, 70, COL_BLUE);
    g_line(210, 70, 250, 100, COL_BLUE);
    g_line(55, 205, 95, 150, COL_RED);
    g_line(95, 150, 130, 135, COL_RED);
    g_line(130, 135, 180, 120, COL_RED);
    g_line(180, 120, 235, 145, COL_RED);
}

static void draw_x_mec_3(void) {
    g_axes(55, 56, 295, 205);
    g_text("sig", 30, 50, COL_GRAY);
    g_text("eps", 270, 210, COL_GRAY);
    g_line(55, 205, 120, 120, COL_BLUE);
    g_line(120, 120, 160, 95, COL_BLUE);
    g_line(160, 95, 210, 70, COL_BLUE);
    g_line(210, 70, 250, 100, COL_BLUE);
}

static void draw_x_gra_1(void) {
    g_axes(55, 56, 295, 205);
    g_text("sig", 30, 50, COL_GRAY);
    g_text("eps", 270, 210, COL_GRAY);
    g_line(55, 205, 110, 120, COL_BLUE);
    g_line(110, 120, 150, 90, COL_BLUE);
    g_line(150, 90, 200, 72, COL_BLUE);
    g_line(200, 72, 245, 95, COL_BLUE);
}

static void draw_cal_6_9(void) {
    g_axes(55, 56, 295, 205);
    g_text("sig", 30, 50, COL_GRAY);
    g_text("eps", 270, 210, COL_GRAY);
    g_line(55, 205, 78, 108, COL_BLUE);
    g_line(78, 108, 102, 90, COL_BLUE);
    g_line(102, 90, 172, 82, COL_BLUE);
    g_line(172, 82, 238, 102, COL_BLUE);
    g_dot(78, 108, COL_RED);
    g_dot(102, 90, COL_RED);
    g_dot(172, 82, COL_RED);
    g_text("E", 60, 150, COL_BLACK);
    g_text("se", 108, 80, COL_RED);
    g_text("LRT", 175, 68, COL_RED);
}

static void draw_cal_6_25(void) {
    g_axes(55, 56, 295, 205);
    g_text("sig", 30, 50, COL_GRAY);
    g_text("eps", 270, 210, COL_GRAY);
    g_line(55, 205, 78, 108, COL_BLUE);
    g_line(78, 108, 102, 90, COL_BLUE);
    g_line(102, 90, 172, 82, COL_BLUE);
    g_line(172, 82, 238, 102, COL_BLUE);
    g_dot(78, 108, COL_RED);
    g_dot(102, 90, COL_RED);
    g_dot(172, 82, COL_RED);
    g_text("E", 60, 150, COL_BLACK);
    g_text("se", 108, 80, COL_RED);
    g_text("LRT", 175, 68, COL_RED);
}

static void draw_cal_6_27(void) {
    g_axes(55, 56, 295, 205);
    g_text("sig", 30, 50, COL_GRAY);
    g_text("eps", 270, 210, COL_GRAY);
    g_line(55, 205, 78, 108, COL_BLUE);
    g_line(78, 108, 102, 90, COL_BLUE);
    g_line(102, 90, 172, 82, COL_BLUE);
    g_line(172, 82, 238, 102, COL_BLUE);
    g_dot(78, 108, COL_RED);
    g_dot(102, 90, COL_RED);
    g_dot(172, 82, COL_RED);
    g_text("E", 60, 150, COL_BLACK);
    g_text("se", 108, 80, COL_RED);
    g_text("LRT", 175, 68, COL_RED);
}

static const TextLine x_est_1_pg0[] = {
    { "O aluminio tem estrutura CFC com", 14, 62, COL_BLACK },
    { "raio atomico R = 0.143 nm.", 14, 82, COL_BLACK },
    { "Calcule o volume Vc da celula", 14, 102, COL_BLACK },
    { "unitaria.", 14, 122, COL_BLACK },
};

static const TextLine x_est_1_pg1[] = {
    { "", 14, 62, COL_BLACK },
};

static const TextLine x_est_1_pg2[] = {
    { "Relacao a-R na CFC:", 14, 62, COL_BLUE },
    { "a = 2 R raiz(2)", 14, 82, COL_BLACK },
    { "Converter R p/ metros:", 14, 102, COL_BLUE },
    { "R = 0.143e-9 m", 14, 122, COL_BLACK },
    { "a = 2*0.143e-9*1.414 = 4.045e-10 m", 14, 142, COL_BLACK },
    { "Volume da celula cubica:", 14, 162, COL_BLUE },
    { "Vc = a^3 = (4.045e-10)^3", 14, 182, COL_BLACK },
};

static const TextLine x_est_1_pg3[] = {
    { "Vc = 6.62e-29 m3", 14, 62, COL_RED },
};

static const TextLine x_est_1_pg4[] = {
    { "Resposta final:", 14, 62, COL_BLUE },
    { "Vc = 6.62e-29 m3", 14, 82, COL_RED },
};

static const Page x_est_1_pages[] = {
    { "Enunciado", "",
      x_est_1_pg0, COUNT(x_est_1_pg0), 0, 0, 0 },
    { "Grafico", "",
      x_est_1_pg1, COUNT(x_est_1_pg1), 0, 0, draw_x_est_1 },
    { "Resolucao", "parte 1/2",
      x_est_1_pg2, COUNT(x_est_1_pg2), 0, 0, 0 },
    { "Resolucao", "parte 2/2",
      x_est_1_pg3, COUNT(x_est_1_pg3), 0, 0, 0 },
    { "Resultado", "Final",
      x_est_1_pg4, COUNT(x_est_1_pg4), "Vc = 6.62e-29 m3", 104, 0 }
};

static const TextLine x_est_2_pg0[] = {
    { "O vanadio (CCC) tem densidade", 14, 62, COL_BLACK },
    { "rho = 5.96 g/cm3 e A = 50.9 g/mol.", 14, 82, COL_BLACK },
    { "Determine o raio atomico R.", 14, 102, COL_BLACK },
};

static const TextLine x_est_2_pg1[] = {
    { "", 14, 62, COL_BLACK },
};

static const TextLine x_est_2_pg2[] = {
    { "Da densidade isola-se Vc (n=2):", 14, 62, COL_BLUE },
    { "Vc = n A / (rho Na)", 14, 82, COL_BLACK },
    { "Vc = 2*50.9/(5.96*6.022e23)", 14, 102, COL_BLACK },
    { "2.838e-23 cm3", 14, 122, COL_RED },
    { "Aresta e raio (CCC):", 14, 142, COL_BLUE },
    { "a = Vc^(1/3) = 3.05e-8 cm", 14, 162, COL_BLACK },
    { "R = a raiz(3)/4", 14, 182, COL_BLACK },
};

static const TextLine x_est_2_pg3[] = {
    { "R = 1.321e-8 cm = 0.1321 nm", 14, 62, COL_RED },
};

static const TextLine x_est_2_pg4[] = {
    { "Resposta final:", 14, 62, COL_BLUE },
    { "R = 0.1321 nm", 14, 82, COL_RED },
};

static const Page x_est_2_pages[] = {
    { "Enunciado", "",
      x_est_2_pg0, COUNT(x_est_2_pg0), 0, 0, 0 },
    { "Grafico", "",
      x_est_2_pg1, COUNT(x_est_2_pg1), 0, 0, draw_x_est_2 },
    { "Resolucao", "parte 1/2",
      x_est_2_pg2, COUNT(x_est_2_pg2), 0, 0, 0 },
    { "Resolucao", "parte 2/2",
      x_est_2_pg3, COUNT(x_est_2_pg3), 0, 0, 0 },
    { "Resultado", "Final",
      x_est_2_pg4, COUNT(x_est_2_pg4), "R = 0.1321 nm", 104, 0 }
};

static const TextLine x_est_3_pg0[] = {
    { "Mostre que o fator de empacotamento", 14, 62, COL_BLACK },
    { "atomico (FEA) da estrutura CFC e", 14, 82, COL_BLACK },
    { "0.74 (4 atomos por celula).", 14, 102, COL_BLACK },
};

static const TextLine x_est_3_pg1[] = {
    { "FEA = Vol. atomos / Vol. celula:", 14, 62, COL_BLUE },
    { "n = 4 atomos; Vat = 4*(4/3)pi R^3", 14, 82, COL_BLACK },
    { "Celula CFC: a = 2R raiz(2)", 14, 102, COL_BLUE },
    { "Vc = a^3 = 16 raiz(2) R^3", 14, 122, COL_BLACK },
    { "FEA = (16/3)pi R^3 / (16 raiz2 R^3)", 14, 142, COL_BLACK },
    { "FEA = pi/(3 raiz2)", 14, 162, COL_BLACK },
    { "FEA = 0.74", 14, 182, COL_RED },
};

static const TextLine x_est_3_pg2[] = {
    { "Resposta final:", 14, 62, COL_BLUE },
    { "FEA = 0.74", 14, 82, COL_RED },
};

static const Page x_est_3_pages[] = {
    { "Enunciado", "",
      x_est_3_pg0, COUNT(x_est_3_pg0), 0, 0, 0 },
    { "Resolucao", "passo a passo",
      x_est_3_pg1, COUNT(x_est_3_pg1), 0, 0, 0 },
    { "Resultado", "Final",
      x_est_3_pg2, COUNT(x_est_3_pg2), "FEA(CFC) = 0.74", 104, 0 }
};

static const TextLine x_den_1_pg0[] = {
    { "Calcule a densidade teorica do", 14, 62, COL_BLACK },
    { "aluminio (CFC): A = 26.982 g/mol,", 14, 82, COL_BLACK },
    { "R = 0.1431 nm, n = 4.", 14, 102, COL_BLACK },
};

static const TextLine x_den_1_pg1[] = {
    { "", 14, 62, COL_BLACK },
};

static const TextLine x_den_1_pg2[] = {
    { "Formula da densidade:", 14, 62, COL_BLUE },
    { "rho = n A / (Vc Na)", 14, 82, COL_BLACK },
    { "Vc da CFC (R em cm):", 14, 102, COL_BLUE },
    { "R = 1.431e-8 cm; a = 2R raiz2", 14, 122, COL_BLACK },
    { "Vc = a^3 = 6.62e-23 cm3", 14, 142, COL_BLACK },
    { "Substituir:", 14, 162, COL_BLUE },
    { "rho = 4*26.982/(6.62e-23*6.022e23)", 14, 182, COL_BLACK },
};

static const TextLine x_den_1_pg3[] = {
    { "rho = 2.70 g/cm3", 14, 62, COL_RED },
};

static const TextLine x_den_1_pg4[] = {
    { "Resposta final:", 14, 62, COL_BLUE },
    { "rho = 2.70 g/cm3", 14, 82, COL_RED },
};

static const Page x_den_1_pages[] = {
    { "Enunciado", "",
      x_den_1_pg0, COUNT(x_den_1_pg0), 0, 0, 0 },
    { "Grafico", "",
      x_den_1_pg1, COUNT(x_den_1_pg1), 0, 0, draw_x_den_1 },
    { "Resolucao", "parte 1/2",
      x_den_1_pg2, COUNT(x_den_1_pg2), 0, 0, 0 },
    { "Resolucao", "parte 2/2",
      x_den_1_pg3, COUNT(x_den_1_pg3), 0, 0, 0 },
    { "Resultado", "Final",
      x_den_1_pg4, COUNT(x_den_1_pg4), "rho = 2.70 g/cm3", 104, 0 }
};

static const TextLine x_dif_1_pg0[] = {
    { "Hidrogenio difunde numa chapa de", 14, 62, COL_BLACK },
    { "Pd de area 0.20 m2. D = 1.0e-8 m2/s,", 14, 82, COL_BLACK },
    { "dC = 1.8 kg/m3 em dx = 5 mm.", 14, 102, COL_BLACK },
    { "Ache a massa por hora.", 14, 122, COL_BLACK },
};

static const TextLine x_dif_1_pg1[] = {
    { "", 14, 62, COL_BLACK },
};

static const TextLine x_dif_1_pg2[] = {
    { "1a Lei de Fick (fluxo):", 14, 62, COL_BLUE },
    { "J = D dC/dx", 14, 82, COL_BLACK },
    { "J = 1.0e-8 * 1.8/0.005", 14, 102, COL_BLACK },
    { "J = 3.6e-6 kg/(m2 s)", 14, 122, COL_RED },
    { "Massa em 1 h (t=3600 s):", 14, 142, COL_BLUE },
    { "M = J A t = 3.6e-6*0.20*3600", 14, 162, COL_BLACK },
    { "M = 2.592e-3 kg/h", 14, 182, COL_RED },
};

static const TextLine x_dif_1_pg3[] = {
    { "Resposta final:", 14, 62, COL_BLUE },
    { "M = 2.592e-3 kg/h", 14, 82, COL_RED },
};

static const Page x_dif_1_pages[] = {
    { "Enunciado", "",
      x_dif_1_pg0, COUNT(x_dif_1_pg0), 0, 0, 0 },
    { "Grafico", "",
      x_dif_1_pg1, COUNT(x_dif_1_pg1), 0, 0, draw_x_dif_1 },
    { "Resolucao", "passo a passo",
      x_dif_1_pg2, COUNT(x_dif_1_pg2), 0, 0, 0 },
    { "Resultado", "Final",
      x_dif_1_pg3, COUNT(x_dif_1_pg3), "M = 2.59e-3 kg/h", 104, 0 }
};

static const TextLine x_dif_2_pg0[] = {
    { "Difusao de N no aco: D = 1.85e-10", 14, 62, COL_BLACK },
    { "m2/s, fluxo J = 1.0e-7 kg/(m2 s).", 14, 82, COL_BLACK },
    { "C cai de 2.0 a 0.5 kg/m3.", 14, 102, COL_BLACK },
    { "Ache a distancia x (perfil linear).", 14, 122, COL_BLACK },
};

static const TextLine x_dif_2_pg1[] = {
    { "", 14, 62, COL_BLACK },
};

static const TextLine x_dif_2_pg2[] = {
    { "Da 1a Lei de Fick isola-se x:", 14, 62, COL_BLUE },
    { "J = D (C0 - Cx)/x", 14, 82, COL_BLACK },
    { "x = D (C0 - Cx)/J", 14, 102, COL_BLACK },
    { "x = 1.85e-10*(2.0-0.5)/1.0e-7", 14, 122, COL_BLACK },
    { "x = 1.85e-10*1.5/1.0e-7", 14, 142, COL_BLACK },
    { "x = 2.775e-3 m = 2.775 mm", 14, 162, COL_RED },
};

static const TextLine x_dif_2_pg3[] = {
    { "Resposta final:", 14, 62, COL_BLUE },
    { "x = 2.775 mm", 14, 82, COL_RED },
};

static const Page x_dif_2_pages[] = {
    { "Enunciado", "",
      x_dif_2_pg0, COUNT(x_dif_2_pg0), 0, 0, 0 },
    { "Grafico", "",
      x_dif_2_pg1, COUNT(x_dif_2_pg1), 0, 0, draw_x_dif_2 },
    { "Resolucao", "passo a passo",
      x_dif_2_pg2, COUNT(x_dif_2_pg2), 0, 0, 0 },
    { "Resultado", "Final",
      x_dif_2_pg3, COUNT(x_dif_2_pg3), "x = 2.775 mm", 104, 0 }
};

static const TextLine x_arr_1_pg0[] = {
    { "Q = 111 kJ/mol. D1 = 6.25e-11 m2/s", 14, 62, COL_BLACK },
    { "a 1400 K. Estime D2 a 1100 K.", 14, 82, COL_BLACK },
    { "(Equacao de Arrhenius)", 14, 102, COL_BLACK },
};

static const TextLine x_arr_1_pg1[] = {
    { "Razao entre dois D (mesmo D0):", 14, 62, COL_BLUE },
    { "ln(D2/D1) = -Q/R (1/T2 - 1/T1)", 14, 82, COL_BLACK },
    { "Q/R = 111000/8.314 = 13351 K", 14, 102, COL_BLACK },
    { "1/1100 - 1/1400 = 1.948e-4", 14, 122, COL_BLACK },
    { "ln(D2/D1) = -13351*1.948e-4=-2.601", 14, 142, COL_BLACK },
    { "D2 = D1 * e^-2.601", 14, 162, COL_BLACK },
    { "D2 = 4.6e-12 m2/s", 14, 182, COL_RED },
};

static const TextLine x_arr_1_pg2[] = {
    { "Resposta final:", 14, 62, COL_BLUE },
    { "D2 = 4.6e-12 m2/s", 14, 82, COL_RED },
};

static const Page x_arr_1_pages[] = {
    { "Enunciado", "",
      x_arr_1_pg0, COUNT(x_arr_1_pg0), 0, 0, 0 },
    { "Resolucao", "passo a passo",
      x_arr_1_pg1, COUNT(x_arr_1_pg1), 0, 0, 0 },
    { "Resultado", "Final",
      x_arr_1_pg2, COUNT(x_arr_1_pg2), "D2 = 4.6e-12 m2/s", 104, 0 }
};

static const TextLine x_arr_2_pg0[] = {
    { "Dois pontos: a 1273 K, D=9.4e-16;", 14, 62, COL_BLACK },
    { "a 1473 K, D=2.4e-14 m2/s.", 14, 82, COL_BLACK },
    { "Ache Q e D0 (reta lnD vs 1/T).", 14, 102, COL_BLACK },
};

static const TextLine x_arr_2_pg1[] = {
    { "", 14, 62, COL_BLACK },
};

static const TextLine x_arr_2_pg2[] = {
    { "Inclinacao da reta lnD vs 1/T:", 14, 62, COL_BLUE },
    { "Q = -R (lnD1 - lnD2)/(1/T1 - 1/T2)", 14, 82, COL_BLACK },
    { "lnD1-lnD2 = ln(9.4e-16/2.4e-14)", 14, 102, COL_BLACK },
    { "-3.24; 1/1273-1/1473=1.067e-4", 14, 122, COL_RED },
    { "Q = -8.314*(-3.24)/1.067e-4", 14, 142, COL_BLACK },
    { "Q = 252550 J/mol", 14, 162, COL_RED },
    { "D0 pela equacao original:", 14, 182, COL_BLUE },
};

static const TextLine x_arr_2_pg3[] = {
    { "D0 = 2.17e-5 m2/s", 14, 62, COL_RED },
};

static const TextLine x_arr_2_pg4[] = {
    { "Resposta final:", 14, 62, COL_BLUE },
    { "Q = 252.5 kJ/mol", 14, 82, COL_RED },
    { "D0 = 2.17e-5 m2/s", 14, 102, COL_RED },
};

static const Page x_arr_2_pages[] = {
    { "Enunciado", "",
      x_arr_2_pg0, COUNT(x_arr_2_pg0), 0, 0, 0 },
    { "Grafico", "",
      x_arr_2_pg1, COUNT(x_arr_2_pg1), 0, 0, draw_x_arr_2 },
    { "Resolucao", "parte 1/2",
      x_arr_2_pg2, COUNT(x_arr_2_pg2), 0, 0, 0 },
    { "Resolucao", "parte 2/2",
      x_arr_2_pg3, COUNT(x_arr_2_pg3), 0, 0, 0 },
    { "Resultado", "Final",
      x_arr_2_pg4, COUNT(x_arr_2_pg4), "Q=252.5 kJ/mol; D0=2.17e-5", 124, 0 }
};

static const TextLine x_dia_1_pg0[] = {
    { "No sistema Pb-Sn, identifique o", 14, 62, COL_BLACK },
    { "ponto eutetico (T e composicao) e", 14, 82, COL_BLACK },
    { "a reacao que ocorre nele.", 14, 102, COL_BLACK },
};

static const TextLine x_dia_1_pg1[] = {
    { "", 14, 62, COL_BLACK },
};

static const TextLine x_dia_1_pg2[] = {
    { "No eutetico o liquido se transforma", 14, 62, COL_BLUE },
    { "em dois solidos ao mesmo tempo:", 14, 82, COL_BLACK },
    { "L -> alpha + beta (resfriando)", 14, 102, COL_BLACK },
    { "Leitura do diagrama Pb-Sn:", 14, 122, COL_BLUE },
    { "temperatura eutetica = 183 C", 14, 142, COL_BLACK },
    { "composicao = 61.9 wt% Sn", 14, 162, COL_RED },
};

static const TextLine x_dia_1_pg3[] = {
    { "Resposta final:", 14, 62, COL_BLUE },
    { "T = 183 C; 61.9 wt% Sn", 14, 82, COL_RED },
    { "L -> alpha + beta", 14, 102, COL_RED },
};

static const Page x_dia_1_pages[] = {
    { "Enunciado", "",
      x_dia_1_pg0, COUNT(x_dia_1_pg0), 0, 0, 0 },
    { "Grafico", "",
      x_dia_1_pg1, COUNT(x_dia_1_pg1), 0, 0, draw_x_dia_1 },
    { "Resolucao", "passo a passo",
      x_dia_1_pg2, COUNT(x_dia_1_pg2), 0, 0, 0 },
    { "Resultado", "Final",
      x_dia_1_pg3, COUNT(x_dia_1_pg3), "Eutetico: 183 C; 61.9% Sn", 124, 0 }
};

static const TextLine x_ala_1_pg0[] = {
    { "Liga Cu-Ni com C0 = 35 wt% Ni numa", 14, 62, COL_BLACK },
    { "regiao alpha+L. A linha de amarracao", 14, 82, COL_BLACK },
    { "da CL = 32 e Calpha = 43 wt% Ni.", 14, 102, COL_BLACK },
    { "Ache as fracoes de L e de alpha.", 14, 122, COL_BLACK },
};

static const TextLine x_ala_1_pg1[] = {
    { "", 14, 62, COL_BLACK },
};

static const TextLine x_ala_1_pg2[] = {
    { "Regra da alavanca (fracao de L):", 14, 62, COL_BLUE },
    { "wL = (Calpha - C0)/(Calpha - CL)", 14, 82, COL_BLACK },
    { "wL = (43 - 35)/(43 - 32)", 14, 102, COL_BLACK },
    { "wL = 8/11 = 0.727 (72.7%)", 14, 122, COL_RED },
    { "Fracao de solido alpha:", 14, 142, COL_BLUE },
    { "wa = (C0 - CL)/(Calpha - CL)", 14, 162, COL_BLACK },
    { "wa = (35 - 32)/11", 14, 182, COL_BLACK },
};

static const TextLine x_ala_1_pg3[] = {
    { "wa = 0.273 (27.3%)", 14, 62, COL_RED },
};

static const TextLine x_ala_1_pg4[] = {
    { "Resposta final:", 14, 62, COL_BLUE },
    { "wL = 72.7%; w(alpha) = 27.3%", 14, 82, COL_RED },
};

static const Page x_ala_1_pages[] = {
    { "Enunciado", "",
      x_ala_1_pg0, COUNT(x_ala_1_pg0), 0, 0, 0 },
    { "Grafico", "",
      x_ala_1_pg1, COUNT(x_ala_1_pg1), 0, 0, draw_x_ala_1 },
    { "Resolucao", "parte 1/2",
      x_ala_1_pg2, COUNT(x_ala_1_pg2), 0, 0, 0 },
    { "Resolucao", "parte 2/2",
      x_ala_1_pg3, COUNT(x_ala_1_pg3), 0, 0, 0 },
    { "Resultado", "Final",
      x_ala_1_pg4, COUNT(x_ala_1_pg4), "wL=72.7%; wa=27.3%", 104, 0 }
};

static const TextLine x_mec_1_pg0[] = {
    { "Curvas tensao-deformacao:", 14, 62, COL_BLACK },
    { "Mat A: 240 MPa a eps = 0.004.", 14, 82, COL_BLACK },
    { "Mat B: 120 MPa a eps = 0.0006.", 14, 102, COL_BLACK },
    { "Compare o modulo de elasticidade E.", 14, 122, COL_BLACK },
};

static const TextLine x_mec_1_pg1[] = {
    { "", 14, 62, COL_BLACK },
};

static const TextLine x_mec_1_pg2[] = {
    { "E = inclinacao da reta elastica:", 14, 62, COL_BLUE },
    { "E = sigma / epsilon", 14, 82, COL_BLACK },
    { "Material A:", 14, 102, COL_BLUE },
    { "E_A = 240/0.004 = 60000 MPa = 60 GPa", 14, 122, COL_BLACK },
    { "Material B:", 14, 142, COL_BLUE },
    { "E_B = 120/0.0006 = 200000 = 200 GPa", 14, 162, COL_BLACK },
    { "B e mais rigido (maior E)", 14, 182, COL_RED },
};

static const TextLine x_mec_1_pg3[] = {
    { "Resposta final:", 14, 62, COL_BLUE },
    { "E_A = 60 GPa; E_B = 200 GPa", 14, 82, COL_RED },
    { "B e mais rigido", 14, 102, COL_RED },
};

static const Page x_mec_1_pages[] = {
    { "Enunciado", "",
      x_mec_1_pg0, COUNT(x_mec_1_pg0), 0, 0, 0 },
    { "Grafico", "",
      x_mec_1_pg1, COUNT(x_mec_1_pg1), 0, 0, draw_x_mec_1 },
    { "Resolucao", "passo a passo",
      x_mec_1_pg2, COUNT(x_mec_1_pg2), 0, 0, 0 },
    { "Resultado", "Final",
      x_mec_1_pg3, COUNT(x_mec_1_pg3), "E_A=60; E_B=200 GPa", 124, 0 }
};

static const TextLine x_mec_2_pg0[] = {
    { "Corpo de prova L0 = 50.8 mm.", 14, 62, COL_BLACK },
    { "Mat A rompe com Lf = 59.182 mm;", 14, 82, COL_BLACK },
    { "Mat B com Lf = 55.88 mm.", 14, 102, COL_BLACK },
    { "Calcule o alongamento percentual.", 14, 122, COL_BLACK },
};

static const TextLine x_mec_2_pg1[] = {
    { "Ductilidade (% alongamento):", 14, 62, COL_BLUE },
    { "%AL = (Lf - L0)/L0 * 100", 14, 82, COL_BLACK },
    { "Material A:", 14, 102, COL_BLUE },
    { "%AL = (59.182-50.8)/50.8*100", 14, 122, COL_BLACK },
    { "16.5 %", 14, 142, COL_RED },
    { "Material B:", 14, 162, COL_BLUE },
    { "%AL = (55.88-50.8)/50.8*100 = 10 %", 14, 182, COL_BLACK },
};

static const TextLine x_mec_2_pg2[] = {
    { "A e mais ductil", 14, 62, COL_RED },
};

static const TextLine x_mec_2_pg3[] = {
    { "Resposta final:", 14, 62, COL_BLUE },
    { "A = 16.5%; B = 10%", 14, 82, COL_RED },
    { "A e mais ductil", 14, 102, COL_RED },
};

static const Page x_mec_2_pages[] = {
    { "Enunciado", "",
      x_mec_2_pg0, COUNT(x_mec_2_pg0), 0, 0, 0 },
    { "Resolucao", "parte 1/2",
      x_mec_2_pg1, COUNT(x_mec_2_pg1), 0, 0, 0 },
    { "Resolucao", "parte 2/2",
      x_mec_2_pg2, COUNT(x_mec_2_pg2), 0, 0, 0 },
    { "Resultado", "Final",
      x_mec_2_pg3, COUNT(x_mec_2_pg3), "A=16.5%; B=10% (A ductil)", 124, 0 }
};

static const TextLine x_mec_3_pg0[] = {
    { "Mat A: sigma_e = 280 MPa, E = 60 GPa.", 14, 62, COL_BLACK },
    { "Mat B: sigma_e = 275 MPa, E = 200", 14, 82, COL_BLACK },
    { "GPa.", 14, 102, COL_BLACK },
    { "Calcule e compare a resiliencia Ur.", 14, 122, COL_BLACK },
};

static const TextLine x_mec_3_pg1[] = {
    { "", 14, 62, COL_BLACK },
};

static const TextLine x_mec_3_pg2[] = {
    { "Resiliencia (area elastica):", 14, 62, COL_BLUE },
    { "Ur = sigma_e^2 / (2 E)", 14, 82, COL_BLACK },
    { "Material A (E=60000 MPa):", 14, 102, COL_BLUE },
    { "Ur = 280^2/(2*60000) = 0.653 MJ/m3", 14, 122, COL_BLACK },
    { "Material B (E=200000 MPa):", 14, 142, COL_BLUE },
    { "Ur = 275^2/(2*200000) = 0.189 MJ/m3", 14, 162, COL_BLACK },
    { "A tem maior resiliencia", 14, 182, COL_RED },
};

static const TextLine x_mec_3_pg3[] = {
    { "Resposta final:", 14, 62, COL_BLUE },
    { "Ur(A) = 0.653 MJ/m3", 14, 82, COL_RED },
    { "Ur(B) = 0.189 MJ/m3", 14, 102, COL_RED },
};

static const Page x_mec_3_pages[] = {
    { "Enunciado", "",
      x_mec_3_pg0, COUNT(x_mec_3_pg0), 0, 0, 0 },
    { "Grafico", "",
      x_mec_3_pg1, COUNT(x_mec_3_pg1), 0, 0, draw_x_mec_3 },
    { "Resolucao", "passo a passo",
      x_mec_3_pg2, COUNT(x_mec_3_pg2), 0, 0, 0 },
    { "Resultado", "Final",
      x_mec_3_pg3, COUNT(x_mec_3_pg3), "Ur: A=0.653; B=0.189 MJ/m3", 124, 0 }
};

static const TextLine x_gra_1_pg0[] = {
    { "Do grafico tensao-deformacao de um", 14, 62, COL_BLACK },
    { "aco, extraia: modulo E, limite de", 14, 82, COL_BLACK },
    { "proporcionalidade, tensao de", 14, 102, COL_BLACK },
    { "escoamento (0.2%) e o limite (LRT).", 14, 122, COL_BLACK },
};

static const TextLine x_gra_1_pg1[] = {
    { "", 14, 62, COL_BLACK },
};

static const TextLine x_gra_1_pg2[] = {
    { "Como ler cada parametro:", 14, 62, COL_BLUE },
    { "E = inclinacao da reta inicial", 14, 82, COL_BLACK },
    { "lim. prop. = fim da reta = 400 MPa", 14, 102, COL_BLACK },
    { "Escoamento: reta a 0.2% (0.002):", 14, 122, COL_BLUE },
    { "sigma_e ~ 550 MPa", 14, 142, COL_BLACK },
    { "LRT = pico da curva:", 14, 162, COL_BLUE },
    { "E=250 GPa; sig_e=550; LRT=570 MPa", 14, 182, COL_RED },
};

static const TextLine x_gra_1_pg3[] = {
    { "Resposta final:", 14, 62, COL_BLUE },
    { "E = 250 GPa; sigma_e = 550 MPa", 14, 82, COL_RED },
    { "LRT = 570 MPa", 14, 102, COL_RED },
};

static const Page x_gra_1_pages[] = {
    { "Enunciado", "",
      x_gra_1_pg0, COUNT(x_gra_1_pg0), 0, 0, 0 },
    { "Grafico", "",
      x_gra_1_pg1, COUNT(x_gra_1_pg1), 0, 0, draw_x_gra_1 },
    { "Resolucao", "passo a passo",
      x_gra_1_pg2, COUNT(x_gra_1_pg2), 0, 0, 0 },
    { "Resultado", "Final",
      x_gra_1_pg3, COUNT(x_gra_1_pg3), "E=250 GPa; se=550; LRT=570", 124, 0 }
};

static const TextLine cal_6_3_pg0[] = {
    { "Corpo de prova de aluminio, secao", 14, 62, COL_BLACK },
    { "reta retangular 10 x 12.7 mm, em", 14, 82, COL_BLACK },
    { "tracao com F = 35500 N (so", 14, 102, COL_BLACK },
    { "elastica). Calcule a deformacao.", 14, 122, COL_BLACK },
};

static const TextLine cal_6_3_pg1[] = {
    { "Tensao: sigma = F/A", 14, 62, COL_BLUE },
    { "A = 10 x 12.7 = 127 mm2", 14, 82, COL_BLACK },
    { "sigma = 35500/127 = 279.5 MPa", 14, 102, COL_BLACK },
    { "Deformacao (E_Al = 69 GPa):", 14, 122, COL_BLUE },
    { "epsilon = sigma/E = 279.5/69000", 14, 142, COL_BLACK },
    { "epsilon = 0.0041", 14, 162, COL_RED },
};

static const TextLine cal_6_3_pg2[] = {
    { "Resposta final:", 14, 62, COL_BLUE },
    { "epsilon = 0.0041", 14, 82, COL_RED },
};

static const Page cal_6_3_pages[] = {
    { "Enunciado", "",
      cal_6_3_pg0, COUNT(cal_6_3_pg0), 0, 0, 0 },
    { "Resolucao", "passo a passo",
      cal_6_3_pg1, COUNT(cal_6_3_pg1), 0, 0, 0 },
    { "Resultado", "Final",
      cal_6_3_pg2, COUNT(cal_6_3_pg2), "epsilon = 0.0041", 104, 0 }
};

static const TextLine cal_6_4_pg0[] = {
    { "Liga de titanio, E = 107 GPa,", 14, 62, COL_BLACK },
    { "diametro d = 3.8 mm, tracao", 14, 82, COL_BLACK },
    { "F = 2000 N (so elastica), com", 14, 102, COL_BLACK },
    { "alongamento maximo dl = 0.42 mm.", 14, 122, COL_BLACK },
    { "Ache o comprimento inicial L0.", 14, 142, COL_BLACK },
};

static const TextLine cal_6_4_pg1[] = {
    { "Tensao: sigma = F/A", 14, 62, COL_BLUE },
    { "A = pi (1.9)^2 = 11.34 mm2", 14, 82, COL_BLACK },
    { "sigma = 2000/11.34 = 176.4 MPa", 14, 102, COL_BLACK },
    { "Deformacao elastica:", 14, 122, COL_BLUE },
    { "eps = sigma/E = 176.4/107000", 14, 142, COL_BLACK },
    { "1.649e-3", 14, 162, COL_RED },
    { "Comprimento: L0 = dl/eps", 14, 182, COL_BLUE },
};

static const TextLine cal_6_4_pg2[] = {
    { "L0 = 0.42/1.649e-3 = 254.7 mm", 14, 62, COL_BLACK },
    { "L0 ~ 250 mm (Callister)", 14, 82, COL_RED },
};

static const TextLine cal_6_4_pg3[] = {
    { "Resposta final:", 14, 62, COL_BLUE },
    { "L0 = 250 mm", 14, 82, COL_RED },
};

static const Page cal_6_4_pages[] = {
    { "Enunciado", "",
      cal_6_4_pg0, COUNT(cal_6_4_pg0), 0, 0, 0 },
    { "Resolucao", "parte 1/2",
      cal_6_4_pg1, COUNT(cal_6_4_pg1), 0, 0, 0 },
    { "Resolucao", "parte 2/2",
      cal_6_4_pg2, COUNT(cal_6_4_pg2), 0, 0, 0 },
    { "Resultado", "Final",
      cal_6_4_pg3, COUNT(cal_6_4_pg3), "L0 = 250 mm", 104, 0 }
};

static const TextLine cal_6_9_pg0[] = {
    { "Liga de aco (curva tensao-deformacao", 14, 62, COL_BLACK },
    { "da Fig.), diametro d = 8.5 mm,", 14, 82, COL_BLACK },
    { "L0 = 75 mm, em tracao com", 14, 102, COL_BLACK },
    { "F = 23500 N. Ache o alongamento dl.", 14, 122, COL_BLACK },
};

static const TextLine cal_6_9_pg1[] = {
    { "", 14, 62, COL_BLACK },
};

static const TextLine cal_6_9_pg2[] = {
    { "Tensao aplicada: sigma = F/A", 14, 62, COL_BLUE },
    { "A = pi (4.25)^2 = 56.7 mm2", 14, 82, COL_BLACK },
    { "sigma = 23500/56.7 = 414 MPa", 14, 102, COL_BLACK },
    { "Regiao elastica: ler eps na Fig.", 14, 122, COL_BLUE },
    { "eps ~ 0.0013", 14, 142, COL_BLACK },
    { "Alongamento: dl = eps * L0", 14, 162, COL_BLUE },
    { "dl = 0.0013 * 75", 14, 182, COL_BLACK },
};

static const TextLine cal_6_9_pg3[] = {
    { "dl = 0.10 mm", 14, 62, COL_RED },
};

static const TextLine cal_6_9_pg4[] = {
    { "Resposta final:", 14, 62, COL_BLUE },
    { "dl = 0.10 mm", 14, 82, COL_RED },
};

static const Page cal_6_9_pages[] = {
    { "Enunciado", "",
      cal_6_9_pg0, COUNT(cal_6_9_pg0), 0, 0, 0 },
    { "Grafico", "",
      cal_6_9_pg1, COUNT(cal_6_9_pg1), 0, 0, draw_cal_6_9 },
    { "Resolucao", "parte 1/2",
      cal_6_9_pg2, COUNT(cal_6_9_pg2), 0, 0, 0 },
    { "Resolucao", "parte 2/2",
      cal_6_9_pg3, COUNT(cal_6_9_pg3), 0, 0, 0 },
    { "Resultado", "Final",
      cal_6_9_pg4, COUNT(cal_6_9_pg4), "dl = 0.10 mm", 104, 0 }
};

static const TextLine cal_6_25_pg0[] = {
    { "A Fig. mostra a curva tensao-", 14, 62, COL_BLACK },
    { "deformacao de uma liga de aco.", 14, 82, COL_BLACK },
    { "Determine: (a) E; (b) limite de", 14, 102, COL_BLACK },
    { "proporcionalidade; (c) escoamento a", 14, 122, COL_BLACK },
    { "0.2%; (d) limite de resistencia LRT.", 14, 142, COL_BLACK },
};

static const TextLine cal_6_25_pg1[] = {
    { "", 14, 62, COL_BLACK },
};

static const TextLine cal_6_25_pg2[] = {
    { "(a) E = inclinacao da reta inicial", 14, 62, COL_BLUE },
    { "E = 250 GPa", 14, 82, COL_RED },
    { "(b) fim da reta (lim. prop.):", 14, 102, COL_BLUE },
    { "400 MPa", 14, 122, COL_RED },
    { "(c) escoamento (offset de 0.2%):", 14, 142, COL_BLUE },
    { "sigma_e = 550 MPa", 14, 162, COL_RED },
    { "(d) pico da curva (LRT):", 14, 182, COL_BLUE },
};

static const TextLine cal_6_25_pg3[] = {
    { "LRT = 570 MPa", 14, 62, COL_RED },
};

static const TextLine cal_6_25_pg4[] = {
    { "Resposta final:", 14, 62, COL_BLUE },
    { "E=250 GPa; lim.prop.=400 MPa", 14, 82, COL_RED },
    { "sigma_e=550 MPa; LRT=570 MPa", 14, 102, COL_RED },
};

static const Page cal_6_25_pages[] = {
    { "Enunciado", "",
      cal_6_25_pg0, COUNT(cal_6_25_pg0), 0, 0, 0 },
    { "Grafico", "",
      cal_6_25_pg1, COUNT(cal_6_25_pg1), 0, 0, draw_cal_6_25 },
    { "Resolucao", "parte 1/2",
      cal_6_25_pg2, COUNT(cal_6_25_pg2), 0, 0, 0 },
    { "Resolucao", "parte 2/2",
      cal_6_25_pg3, COUNT(cal_6_25_pg3), 0, 0, 0 },
    { "Resultado", "Final",
      cal_6_25_pg4, COUNT(cal_6_25_pg4), "E=250G; se=550; LRT=570 MPa", 124, 0 }
};

static const TextLine cal_6_27_pg0[] = {
    { "Carga F = 44500 N num corpo de prova", 14, 62, COL_BLACK },
    { "cilindrico de aco (Fig.), diametro", 14, 82, COL_BLACK },
    { "d = 10 mm. (a) deformacao elastica ou", 14, 102, COL_BLACK },
    { "plastica? (b) com L0 = 500 mm, ache", 14, 122, COL_BLACK },
    { "o alongamento dl.", 14, 142, COL_BLACK },
};

static const TextLine cal_6_27_pg1[] = {
    { "", 14, 62, COL_BLACK },
};

static const TextLine cal_6_27_pg2[] = {
    { "Tensao: sigma = F/A", 14, 62, COL_BLUE },
    { "A = pi (5)^2 = 78.54 mm2", 14, 82, COL_BLACK },
    { "sigma = 44500/78.54 = 567 MPa", 14, 102, COL_BLACK },
    { "(a) 567 > escoamento (550 MPa):", 14, 122, COL_BLUE },
    { "deformacao PLASTICA", 14, 142, COL_RED },
    { "(b) ler eps na Fig.: eps ~ 0.008", 14, 162, COL_BLUE },
    { "dl = eps * L0 = 0.008 * 500", 14, 182, COL_BLACK },
};

static const TextLine cal_6_27_pg3[] = {
    { "dl = 4 mm", 14, 62, COL_RED },
};

static const TextLine cal_6_27_pg4[] = {
    { "Resposta final:", 14, 62, COL_BLUE },
    { "(a) plastica (sigma > sigma_e)", 14, 82, COL_RED },
    { "(b) dl = 4 mm", 14, 102, COL_RED },
};

static const Page cal_6_27_pages[] = {
    { "Enunciado", "",
      cal_6_27_pg0, COUNT(cal_6_27_pg0), 0, 0, 0 },
    { "Grafico", "",
      cal_6_27_pg1, COUNT(cal_6_27_pg1), 0, 0, draw_cal_6_27 },
    { "Resolucao", "parte 1/2",
      cal_6_27_pg2, COUNT(cal_6_27_pg2), 0, 0, 0 },
    { "Resolucao", "parte 2/2",
      cal_6_27_pg3, COUNT(cal_6_27_pg3), 0, 0, 0 },
    { "Resultado", "Final",
      cal_6_27_pg4, COUNT(cal_6_27_pg4), "plastica; dl = 4 mm", 124, 0 }
};

static const TextLine cal_6_31_pg0[] = {
    { "Corpo de prova cilindrico: d0 = 12.8", 14, 62, COL_BLACK },
    { "mm, L0 = 50.80 mm. Na fratura:", 14, 82, COL_BLACK },
    { "df = 6.60 mm e Lf = 72.14 mm.", 14, 102, COL_BLACK },
    { "Calcule a ductilidade: %RA e %AL.", 14, 122, COL_BLACK },
};

static const TextLine cal_6_31_pg1[] = {
    { "Reducao percentual de area (%RA):", 14, 62, COL_BLUE },
    { "%RA = (d0^2 - df^2)/d0^2 * 100", 14, 82, COL_BLACK },
    { "(12.8^2 - 6.60^2)/12.8^2 * 100", 14, 102, COL_RED },
    { "%RA = 73.4 %", 14, 122, COL_RED },
    { "Alongamento percentual (%AL):", 14, 142, COL_BLUE },
    { "%AL = (Lf - L0)/L0 * 100", 14, 162, COL_BLACK },
    { "(72.14-50.80)/50.80 * 100", 14, 182, COL_RED },
};

static const TextLine cal_6_31_pg2[] = {
    { "%AL = 42 %", 14, 62, COL_RED },
};

static const TextLine cal_6_31_pg3[] = {
    { "Resposta final:", 14, 62, COL_BLUE },
    { "%RA = 73.4%; %AL = 42%", 14, 82, COL_RED },
};

static const Page cal_6_31_pages[] = {
    { "Enunciado", "",
      cal_6_31_pg0, COUNT(cal_6_31_pg0), 0, 0, 0 },
    { "Resolucao", "parte 1/2",
      cal_6_31_pg1, COUNT(cal_6_31_pg1), 0, 0, 0 },
    { "Resolucao", "parte 2/2",
      cal_6_31_pg2, COUNT(cal_6_31_pg2), 0, 0, 0 },
    { "Resultado", "Final",
      cal_6_31_pg3, COUNT(cal_6_31_pg3), "%RA=73.4%; %AL=42%", 104, 0 }
};

static const Exercise exs_estruturas[] = {
    { "Ex 1: Vc do Al (CFC)", x_est_1_pages, COUNT(x_est_1_pages) },
    { "Ex 2: R do V (CCC)", x_est_2_pages, COUNT(x_est_2_pages) },
    { "Ex 3: FEA da CFC", x_est_3_pages, COUNT(x_est_3_pages) },
};

static const Exercise exs_densidade[] = {
    { "Ex 1: Densidade do Al", x_den_1_pages, COUNT(x_den_1_pages) },
};

static const Exercise exs_difusao[] = {
    { "Ex 1: H em chapa de Pd", x_dif_1_pages, COUNT(x_dif_1_pages) },
    { "Ex 2: Profundidade x", x_dif_2_pages, COUNT(x_dif_2_pages) },
};

static const Exercise exs_arrhenius[] = {
    { "Ex 1: D do C no Cr", x_arr_1_pages, COUNT(x_arr_1_pages) },
    { "Ex 2: Q e D0 (Fe em Ni)", x_arr_2_pages, COUNT(x_arr_2_pages) },
};

static const Exercise exs_diagramas[] = {
    { "Ex 1: Eutetico Pb-Sn", x_dia_1_pages, COUNT(x_dia_1_pages) },
};

static const Exercise exs_alavanca[] = {
    { "Ex 1: Alavanca Cu-Ni", x_ala_1_pages, COUNT(x_ala_1_pages) },
};

static const Exercise exs_mecanicas[] = {
    { "Ex 1: Modulo E (A e B)", x_mec_1_pages, COUNT(x_mec_1_pages) },
    { "Ex 2: Ductilidade %AL", x_mec_2_pages, COUNT(x_mec_2_pages) },
    { "Ex 3: Resiliencia Ur", x_mec_3_pages, COUNT(x_mec_3_pages) },
};

static const Exercise exs_graficos[] = {
    { "Ex 1: Leitura do grafico", x_gra_1_pages, COUNT(x_gra_1_pages) },
};

static const Exercise exs_callister[] = {
    { "6.3: Deformacao do Al", cal_6_3_pages, COUNT(cal_6_3_pages) },
    { "6.4: Comprimento L0 (Ti)", cal_6_4_pages, COUNT(cal_6_4_pages) },
    { "6.9: Alongamento (aco)", cal_6_9_pages, COUNT(cal_6_9_pages) },
    { "6.25: Ler a Fig. (aco)", cal_6_25_pages, COUNT(cal_6_25_pages) },
    { "6.27: Elastica ou plastica", cal_6_27_pages, COUNT(cal_6_27_pages) },
    { "6.31: Ductilidade", cal_6_31_pages, COUNT(cal_6_31_pages) },
};

static const Topic exerc_topics[] = {
    { "Estruturas", exs_estruturas, COUNT(exs_estruturas) },
    { "Densidade", exs_densidade, COUNT(exs_densidade) },
    { "Difusao", exs_difusao, COUNT(exs_difusao) },
    { "Arrhenius", exs_arrhenius, COUNT(exs_arrhenius) },
    { "Diagramas", exs_diagramas, COUNT(exs_diagramas) },
    { "Alavanca", exs_alavanca, COUNT(exs_alavanca) },
    { "Mecanicas", exs_mecanicas, COUNT(exs_mecanicas) },
    { "Graficos", exs_graficos, COUNT(exs_graficos) },
    { "Callister", exs_callister, COUNT(exs_callister) },
};

const Group exerc_group = { "Exercicios", exerc_topics, COUNT(exerc_topics) };
