#include "app.h"

/* Generated by tools/gen_icm.py. Do not edit by hand. */

#define COUNT(a) ((uint8_t)(sizeof(a) / sizeof((a)[0])))

static const TextLine teo_estruturas_pg0[] = {
    { "Relacao aresta a - raio R:", 14, 62, COL_BLUE },
    { "CFC: a = 2 R raiz(2)", 14, 82, COL_BLACK },
    { "CCC: a = 4 R / raiz(3)", 14, 102, COL_BLACK },
    { "HC:  a = 2 R (plano basal)", 14, 122, COL_BLACK },
    { "Atomos por celula (n):", 14, 142, COL_BLUE },
    { "CFC n=4; CCC n=2", 14, 162, COL_BLACK },
    { "Fator de empacotamento (FEA):", 14, 182, COL_BLUE },
};

static const Page teo_estruturas_pages[] = {
    { "Celulas unitarias", "CFC, CCC, HC",
      teo_estruturas_pg0, COUNT(teo_estruturas_pg0), 0, 0, 0 }
};

static const TextLine teo_densidade_pg0[] = {
    { "Densidade teorica:", 14, 62, COL_BLUE },
    { "rho = n A / (Vc Na)", 14, 82, COL_BLACK },
    { "n = atomos/celula; A = massa molar", 14, 102, COL_BLACK },
    { "Vc = a^3 ; Na = 6.022e23", 14, 122, COL_BLACK },
    { "Unidades:", 14, 142, COL_BLUE },
    { "1 nm = 1e-7 cm (p/ g/cm3)", 14, 162, COL_BLACK },
    { "use A em g/mol e R em cm", 14, 182, COL_BLACK },
};

static const Page teo_densidade_pages[] = {
    { "Massa especifica", "rho",
      teo_densidade_pg0, COUNT(teo_densidade_pg0), 0, 0, 0 }
};

static const TextLine teo_difusao_pg0[] = {
    { "Fluxo de difusao:", 14, 62, COL_BLUE },
    { "J = D (CA - CB)/dx", 14, 82, COL_BLACK },
    { "Massa que atravessa:", 14, 102, COL_BLUE },
    { "M = J A t   (t em segundos)", 14, 122, COL_BLACK },
    { "1 h = 3600 s", 14, 142, COL_BLACK },
    { "Profundidade (perfil linear):", 14, 162, COL_BLUE },
    { "x = D (C0 - Cx)/J", 14, 182, COL_BLACK },
};

static const Page teo_difusao_pages[] = {
    { "1a Lei de Fick", "regime estacionario",
      teo_difusao_pg0, COUNT(teo_difusao_pg0), 0, 0, 0 }
};

static const TextLine teo_arrhenius_pg0[] = {
    { "Coeficiente de difusao:", 14, 62, COL_BLUE },
    { "D = D0 exp(-Q/(R T))", 14, 82, COL_BLACK },
    { "R = 8.314 J/(mol K); T em Kelvin", 14, 102, COL_BLACK },
    { "T(K) = T(C) + 273", 14, 122, COL_BLACK },
    { "Dois pontos (D1,T1),(D2,T2):", 14, 142, COL_BLUE },
    { "Q = -R (lnD1-lnD2)/(1/T1-1/T2)", 14, 162, COL_BLACK },
    { "se Q vier em kJ, x1000 -> J", 14, 182, COL_BLACK },
};

static const Page teo_arrhenius_pages[] = {
    { "Equacao de Arrhenius", "D(T)",
      teo_arrhenius_pg0, COUNT(teo_arrhenius_pg0), 0, 0, 0 }
};

static const TextLine teo_diagramas_pg0[] = {
    { "Definicoes:", 14, 62, COL_BLUE },
    { "liquidus: acima so liquido L", 14, 82, COL_BLACK },
    { "solidus: abaixo so solido alpha", 14, 102, COL_BLACK },
    { "Eutetico:", 14, 122, COL_BLUE },
    { "L -> alpha + beta (ponto fixo)", 14, 142, COL_BLACK },
    { "Pb-Sn: 183 C e 61.9 wt% Sn", 14, 162, COL_BLACK },
};

static const Page teo_diagramas_pages[] = {
    { "Linhas e fases", "liquidus/solidus",
      teo_diagramas_pg0, COUNT(teo_diagramas_pg0), 0, 0, 0 }
};

static const TextLine teo_alavanca_pg0[] = {
    { "Na regiao bifasica alpha + L:", 14, 62, COL_BLUE },
    { "wL = (Ca - C0)/(Ca - CL)", 14, 82, COL_BLACK },
    { "w(alpha) = (C0 - CL)/(Ca - CL)", 14, 102, COL_BLACK },
    { "C0 = composicao da liga", 14, 122, COL_BLUE },
    { "CL = liquidus; Ca = solidus", 14, 142, COL_BLACK },
    { "soma das fracoes = 1", 14, 162, COL_BLACK },
};

static const Page teo_alavanca_pages[] = {
    { "Fracoes de fase", "lever rule",
      teo_alavanca_pg0, COUNT(teo_alavanca_pg0), 0, 0, 0 }
};

static const TextLine teo_mecanicas_pg0[] = {
    { "Modulo de elasticidade:", 14, 62, COL_BLUE },
    { "E = sigma / epsilon (reta inicial)", 14, 82, COL_BLACK },
    { "Tensao de escoamento sigma_e:", 14, 102, COL_BLUE },
    { "inicio da deformacao permanente", 14, 122, COL_BLACK },
    { "LRT = pico da curva (resistencia)", 14, 142, COL_BLACK },
    { "Ductilidade e resiliencia:", 14, 162, COL_BLUE },
    { "%AL = (Lf-L0)/L0 *100", 14, 182, COL_BLACK },
};

static const Page teo_mecanicas_pages[] = {
    { "Tensao-deformacao", "parametros",
      teo_mecanicas_pg0, COUNT(teo_mecanicas_pg0), 0, 0, 0 }
};

static const Exercise teo_estruturas_ex[] = {
    { "Estruturas cristalinas", teo_estruturas_pages, COUNT(teo_estruturas_pages) },
};

static const Exercise teo_densidade_ex[] = {
    { "Densidade teorica", teo_densidade_pages, COUNT(teo_densidade_pages) },
};

static const Exercise teo_difusao_ex[] = {
    { "Difusao (Fick)", teo_difusao_pages, COUNT(teo_difusao_pages) },
};

static const Exercise teo_arrhenius_ex[] = {
    { "Difusao x temperatura", teo_arrhenius_pages, COUNT(teo_arrhenius_pages) },
};

static const Exercise teo_diagramas_ex[] = {
    { "Diagramas de fase", teo_diagramas_pages, COUNT(teo_diagramas_pages) },
};

static const Exercise teo_alavanca_ex[] = {
    { "Regra da alavanca", teo_alavanca_pages, COUNT(teo_alavanca_pages) },
};

static const Exercise teo_mecanicas_ex[] = {
    { "Propriedades mecanicas", teo_mecanicas_pages, COUNT(teo_mecanicas_pages) },
};

static const Topic teoria_topics[] = {
    { "Estruturas", teo_estruturas_ex, COUNT(teo_estruturas_ex) },
    { "Densidade", teo_densidade_ex, COUNT(teo_densidade_ex) },
    { "Difusao", teo_difusao_ex, COUNT(teo_difusao_ex) },
    { "Arrhenius", teo_arrhenius_ex, COUNT(teo_arrhenius_ex) },
    { "Diagramas", teo_diagramas_ex, COUNT(teo_diagramas_ex) },
    { "Alavanca", teo_alavanca_ex, COUNT(teo_alavanca_ex) },
    { "Mecanicas", teo_mecanicas_ex, COUNT(teo_mecanicas_ex) },
};

const Group teoria_group = { "Teoria", teoria_topics, COUNT(teoria_topics) };
